spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect